import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ken Smith Porfolio</title>
        <meta name="description" content="Generated by create-next-app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>

      <div>SYKE GET REKT NOOB</div>
    </div>
  );
}
